/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardTimecardsImport } from './routes/_dashboard/timecards'
import { Route as DashboardSettingsImport } from './routes/_dashboard/settings'
import { Route as DashboardProfileImport } from './routes/_dashboard/profile'
import { Route as DashboardOrdersImport } from './routes/_dashboard/orders'
import { Route as DashboardMenuImport } from './routes/_dashboard/menu'
import { Route as DashboardHomeImport } from './routes/_dashboard/home'
import { Route as DashboardFinancesImport } from './routes/_dashboard/finances'
import { Route as DashboardEmployeesImport } from './routes/_dashboard/employees'
import { Route as DashboardBackstockImport } from './routes/_dashboard/backstock'
import { Route as authResetPasswordImport } from './routes/(auth)/resetPassword'
import { Route as authLoggedOutImport } from './routes/(auth)/loggedOut'
import { Route as authChangePasswordImport } from './routes/(auth)/changePassword'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardTimecardsRoute = DashboardTimecardsImport.update({
  id: '/timecards',
  path: '/timecards',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardProfileRoute = DashboardProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOrdersRoute = DashboardOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardMenuRoute = DashboardMenuImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardHomeRoute = DashboardHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFinancesRoute = DashboardFinancesImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardEmployeesRoute = DashboardEmployeesImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBackstockRoute = DashboardBackstockImport.update({
  id: '/backstock',
  path: '/backstock',
  getParentRoute: () => DashboardRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/(auth)/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRoute,
} as any)

const authLoggedOutRoute = authLoggedOutImport.update({
  id: '/(auth)/loggedOut',
  path: '/loggedOut',
  getParentRoute: () => rootRoute,
} as any)

const authChangePasswordRoute = authChangePasswordImport.update({
  id: '/(auth)/changePassword',
  path: '/changePassword',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/changePassword': {
      id: '/(auth)/changePassword'
      path: '/changePassword'
      fullPath: '/changePassword'
      preLoaderRoute: typeof authChangePasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/loggedOut': {
      id: '/(auth)/loggedOut'
      path: '/loggedOut'
      fullPath: '/loggedOut'
      preLoaderRoute: typeof authLoggedOutImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/resetPassword': {
      id: '/(auth)/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/backstock': {
      id: '/_dashboard/backstock'
      path: '/backstock'
      fullPath: '/backstock'
      preLoaderRoute: typeof DashboardBackstockImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/employees': {
      id: '/_dashboard/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof DashboardEmployeesImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/finances': {
      id: '/_dashboard/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof DashboardFinancesImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/menu': {
      id: '/_dashboard/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof DashboardMenuImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/orders': {
      id: '/_dashboard/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DashboardOrdersImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/timecards': {
      id: '/_dashboard/timecards'
      path: '/timecards'
      fullPath: '/timecards'
      preLoaderRoute: typeof DashboardTimecardsImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardBackstockRoute: typeof DashboardBackstockRoute
  DashboardEmployeesRoute: typeof DashboardEmployeesRoute
  DashboardFinancesRoute: typeof DashboardFinancesRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTimecardsRoute: typeof DashboardTimecardsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBackstockRoute: DashboardBackstockRoute,
  DashboardEmployeesRoute: DashboardEmployeesRoute,
  DashboardFinancesRoute: DashboardFinancesRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTimecardsRoute: DashboardTimecardsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof DashboardRouteWithChildren
  '/test': typeof TestRoute
  '/changePassword': typeof authChangePasswordRoute
  '/loggedOut': typeof authLoggedOutRoute
  '/resetPassword': typeof authResetPasswordRoute
  '/backstock': typeof DashboardBackstockRoute
  '/employees': typeof DashboardEmployeesRoute
  '/finances': typeof DashboardFinancesRoute
  '/home': typeof DashboardHomeRoute
  '/menu': typeof DashboardMenuRoute
  '/orders': typeof DashboardOrdersRoute
  '/profile': typeof DashboardProfileRoute
  '/settings': typeof DashboardSettingsRoute
  '/timecards': typeof DashboardTimecardsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof DashboardRouteWithChildren
  '/test': typeof TestRoute
  '/changePassword': typeof authChangePasswordRoute
  '/loggedOut': typeof authLoggedOutRoute
  '/resetPassword': typeof authResetPasswordRoute
  '/backstock': typeof DashboardBackstockRoute
  '/employees': typeof DashboardEmployeesRoute
  '/finances': typeof DashboardFinancesRoute
  '/home': typeof DashboardHomeRoute
  '/menu': typeof DashboardMenuRoute
  '/orders': typeof DashboardOrdersRoute
  '/profile': typeof DashboardProfileRoute
  '/settings': typeof DashboardSettingsRoute
  '/timecards': typeof DashboardTimecardsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/test': typeof TestRoute
  '/(auth)/changePassword': typeof authChangePasswordRoute
  '/(auth)/loggedOut': typeof authLoggedOutRoute
  '/(auth)/resetPassword': typeof authResetPasswordRoute
  '/_dashboard/backstock': typeof DashboardBackstockRoute
  '/_dashboard/employees': typeof DashboardEmployeesRoute
  '/_dashboard/finances': typeof DashboardFinancesRoute
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_dashboard/menu': typeof DashboardMenuRoute
  '/_dashboard/orders': typeof DashboardOrdersRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/timecards': typeof DashboardTimecardsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/test'
    | '/changePassword'
    | '/loggedOut'
    | '/resetPassword'
    | '/backstock'
    | '/employees'
    | '/finances'
    | '/home'
    | '/menu'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/timecards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/test'
    | '/changePassword'
    | '/loggedOut'
    | '/resetPassword'
    | '/backstock'
    | '/employees'
    | '/finances'
    | '/home'
    | '/menu'
    | '/orders'
    | '/profile'
    | '/settings'
    | '/timecards'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/test'
    | '/(auth)/changePassword'
    | '/(auth)/loggedOut'
    | '/(auth)/resetPassword'
    | '/_dashboard/backstock'
    | '/_dashboard/employees'
    | '/_dashboard/finances'
    | '/_dashboard/home'
    | '/_dashboard/menu'
    | '/_dashboard/orders'
    | '/_dashboard/profile'
    | '/_dashboard/settings'
    | '/_dashboard/timecards'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  TestRoute: typeof TestRoute
  authChangePasswordRoute: typeof authChangePasswordRoute
  authLoggedOutRoute: typeof authLoggedOutRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  TestRoute: TestRoute,
  authChangePasswordRoute: authChangePasswordRoute,
  authLoggedOutRoute: authLoggedOutRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dashboard",
        "/test",
        "/(auth)/changePassword",
        "/(auth)/loggedOut",
        "/(auth)/resetPassword"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/backstock",
        "/_dashboard/employees",
        "/_dashboard/finances",
        "/_dashboard/home",
        "/_dashboard/menu",
        "/_dashboard/orders",
        "/_dashboard/profile",
        "/_dashboard/settings",
        "/_dashboard/timecards"
      ]
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/(auth)/changePassword": {
      "filePath": "(auth)/changePassword.tsx"
    },
    "/(auth)/loggedOut": {
      "filePath": "(auth)/loggedOut.tsx"
    },
    "/(auth)/resetPassword": {
      "filePath": "(auth)/resetPassword.tsx"
    },
    "/_dashboard/backstock": {
      "filePath": "_dashboard/backstock.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/employees": {
      "filePath": "_dashboard/employees.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/finances": {
      "filePath": "_dashboard/finances.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/home": {
      "filePath": "_dashboard/home.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/menu": {
      "filePath": "_dashboard/menu.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/orders": {
      "filePath": "_dashboard/orders.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/profile": {
      "filePath": "_dashboard/profile.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/settings": {
      "filePath": "_dashboard/settings.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/timecards": {
      "filePath": "_dashboard/timecards.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
